---
- hosts: my.laptop
  name: Debug with env vars example
  gather_facts: False
  vars_files:
    - vars/deug-vars.yml
  vars:
    full_name: "{{ first_name}} {{ last_name }}"
  tasks:
  - name: Debug message with env vars
    debug:
      msg: "Welcome {{ full_name }}"
